server:
  port: 8080
  http2:
    enabled: true

spring:
  application:
    name: raider-chat
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate